package main

const(
   DEBUG = true
   DEBUG_LEVEL = 4

	FINGERPRINT_OK                 = 0x00
	FINGERPRINT_PACKETRECIEVEERR   = 0x01
	FINGERPRINT_NOFINGER           = 0x02
	FINGERPRINT_IMAGEFAIL          = 0x03
	FINGERPRINT_IMAGEMESS          = 0x06
	FINGERPRINT_FEATUREFAIL        = 0x07
	FINGERPRINT_NOMATCH            = 0x08
	FINGERPRINT_NOTFOUND           = 0x09
	FINGERPRINT_ENROLLMISMATCH     = 0x0A
	FINGERPRINT_BADLOCATION        = 0x0B
	FINGERPRINT_DBRANGEFAIL        = 0x0C
	FINGERPRINT_UPLOADFEATUREFAIL  = 0x0D
	FINGERPRINT_PACKETRESPONSEFAIL = 0x0E
	FINGERPRINT_UPLOADFAIL         = 0x0F
	FINGERPRINT_DELETEFAIL         = 0x10
	FINGERPRINT_DBCLEARFAIL        = 0x11
	FINGERPRINT_PASSFAIL           = 0x13
	FINGERPRINT_INVALIDIMAGE       = 0x15
	FINGERPRINT_FLASHERR           = 0x18
	FINGERPRINT_INVALIDREG         = 0x1A
	FINGERPRINT_ADDRCODE           = 0x20
	FINGERPRINT_PASSVERIFY         = 0x21
	FINGERPRINT_TIMEOUT            = 0x22
	FINGERPRINT_STARTCODE          = 0xEF01

	FINGERPRINT_COMMANDPACKET = 0x01
	FINGERPRINT_DATAPACKET    = 0x20
	FINGERPRINT_ACKPACKET     = 0x70
	FINGERPRINT_ENDPACKET     = 0x80

	FINGERPRINT_GETIMAGE = 0x01
	FINGERPRINT_IMAGE2TZ = 0x02
   FINGERPRINT_HISPEEDSEARCH = 0x04
   FINGERPRINT_REGMODEL = 0x05
   FINGERPRINT_STORE = 0x06
   FINGERPRINT_DELETE = 0x0c
   FINGERPRINT_EMPTY = 0x0D
)
